wechatpay:
  app-id: ${WECHAT_PAY_APP_ID:}
  app-secret: ${WECHAT_PAY_APP_SECRET:}
  mch-id: ${WECHAT_PAY_MCH_ID:}
  mch-serial-no: ${WECHAT_PAY_MCH_SERIAL_NO:}
  private-key: ${WECHAT_PAY_PRIVATE_KEY:}
  platform-public-key: ${WECHAT_PAY_PLATFORM_PUBLIC_KEY:}
  api-v3-key: ${WECHAT_PAY_API_V3_KEY:}
  notify-url: ${WECHAT_PAY_NOTIFY_URL:https://xinglianjia.cn:6888/starhome/wechat/pay/notify}
